# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d9uc3t7lk1mc73efis60-a.oregon-postgres.render.com/donadores_entidades_ohrt_0m0w}
spring.datasource.username=${DB_USERNAME:donadores_entidades_ohrt_user}
spring.datasource.password=${DB_PASSWORD:8IPehHyiXQM6gC76FZK5vQSBV9zq9xB6}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Datadog Metrics Configuration
management.datadog.metrics.export.api-key=${DD_API_KEY:4ed06f324d371709f46dc83dd526bb3f}
management.datadog.metrics.export.uri=https://api.us5.datadoghq.com
management.datadog.metrics.export.step=10s
management.datadog.metrics.export.enabled=${DD_ENABLED:true}

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true

# Server Configuration for Dockerfile
server.port=${PORT:8080}

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/docs

# Incentivos Service
incentivos.url=${INCENTIVOS_URL:https://incentivos-nhyc.onrender.com}

# Telegram Bot
telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
telegram.bot.username=${TELEGRAM_BOT_USERNAME:DonaTrackBot}

# URLs de los otros módulos
services.donaciones.url=${DONACIONES_URL:https://marco-maggio-springboot-api-entrega2-dsi.onrender.com}
services.logistica.url=${LOGISTICA_URL:https://logistica-v3xw.onrender.com}
