# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://dpg-d8jk4l0g4nts73cei0e0-a.oregon-postgres.render.com/donadores_entidades_ohrt}
spring.datasource.username=${DB_USERNAME:donadores_entidades_ohrt_user}
spring.datasource.password=${DB_PASSWORD:JwgK7ru49gRvGHOvG0NFWx4pe6NNFMN7}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true

# Server Configuration for Dockerfile
server.port=${PORT:8080}

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/docs
